from operator import attrgetter
from pathlib import Path
from textwrap import dedent
from typing import Any

import pytest
import requests_mock
from _pytest.monkeypatch import MonkeyPatch
from requests_mock import Mocker

from diff_poetry_lock import __version__
from diff_poetry_lock.github import MAGIC_COMMENT_IDENTIFIER, GithubApi
from diff_poetry_lock.run_poetry import PackageSummary, diff, do_diff, format_comment, load_packages, main
from diff_poetry_lock.settings import GitHubActionsSettings, Settings

TESTFILE_1 = Path("diff_poetry_lock/test/res/poetry1.lock")
TESTFILE_2 = Path("diff_poetry_lock/test/res/poetry2.lock")


@pytest.fixture
def cfg() -> Settings:
    return create_settings()


@pytest.fixture
def data1() -> bytes:
    return load_file(TESTFILE_1)


@pytest.fixture
def data2() -> bytes:
    return load_file(TESTFILE_2)


def test_settings(monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("GITHUB_EVENT_NAME", "pull_request")
    monkeypatch.setenv("GITHUB_REF", "refs/pull/1/merge")
    monkeypatch.setenv("GITHUB_REPOSITORY", "account/repo")
    monkeypatch.setenv("INPUT_GITHUB_TOKEN", "foobar")
    monkeypatch.setenv("GITHUB_BASE_REF", "main")

    s = GitHubActionsSettings()

    assert s.pr_num == "1"


def test_settings_not_pr(monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("GITHUB_EVENT_NAME", "push")
    monkeypatch.setenv("GITHUB_REF", "refs/pull/1/merge")
    monkeypatch.setenv("GITHUB_REPOSITORY", "account/repo")
    monkeypatch.setenv("INPUT_GITHUB_TOKEN", "foobar")
    monkeypatch.setenv("GITHUB_BASE_REF", "main")

    with pytest.raises(SystemExit) as pytest_wrapped_e:
        main()

    assert pytest_wrapped_e.type is SystemExit
    assert pytest_wrapped_e.value.code == 0


def test_diff() -> None:
    old = load_packages(TESTFILE_1)
    new = load_packages(TESTFILE_2)

    summary: list[PackageSummary] = sorted(diff(old, new), key=attrgetter("name"))

    expected = [
        PackageSummary(name="certifi", old_version="2022.12.7", new_version="2022.12.7"),
        PackageSummary(name="charset-normalizer", old_version="3.1.0", new_version="3.1.0"),
        PackageSummary(name="idna", old_version="3.4", new_version="3.4"),
        PackageSummary(name="pydantic", old_version="1.10.6", new_version=None),
        PackageSummary(name="requests", old_version="2.28.2", new_version="2.28.2"),
        PackageSummary(name="typing-extensions", old_version="4.5.0", new_version=None),
        PackageSummary(name="urllib3", old_version="1.26.15", new_version="1.26.14"),
    ]
    assert summary == expected

    expected_comment = f"""\
    ### Detected 3 changes to dependencies in Poetry lockfile

    From base new-sha to target old-sha:

    Removed **pydantic** (1.10.6)
    Removed **typing-extensions** (4.5.0)
    Updated **urllib3** (1.26.15 -> 1.26.14)

    *(0 added, 2 removed, 1 updated, 4 not changed)*

    <small>Generated by diff-poetry-lock {__version__}</small>
    """
    assert (
        format_comment(
            summary,
            base_commit_hash="new-sha",
            target_commit_hash="old-sha",
        )
        or ""
    ).strip() == dedent(expected_comment).strip()


def test_request_headers_method() -> None:
    headers = GithubApi.request_headers("sekret-token")
    assert headers["Authorization"] == "Bearer sekret-token"
    assert headers["Accept"] == "application/vnd.github+json"


@pytest.mark.parametrize(
    ("api_url", "expected_graphql_url"),
    [
        ("https://api.github.com", "https://api.github.com/graphql"),
        ("https://git.target.com/api/v3", "https://git.target.com/api/graphql"),
    ],
)
def test_graphql_url_resolution(api_url: str, expected_graphql_url: str) -> None:
    cfg = create_settings(api_url=api_url)
    api = GithubApi(cfg)

    assert api.graphql_url() == expected_graphql_url


def test_diff_2() -> None:
    old = load_packages(TESTFILE_2)
    new = load_packages(TESTFILE_1)

    summary: list[PackageSummary] = sorted(diff(old, new), key=attrgetter("name"))

    expected = [
        PackageSummary(name="certifi", old_version="2022.12.7", new_version="2022.12.7"),
        PackageSummary(name="charset-normalizer", old_version="3.1.0", new_version="3.1.0"),
        PackageSummary(name="idna", old_version="3.4", new_version="3.4"),
        PackageSummary(name="pydantic", old_version=None, new_version="1.10.6"),
        PackageSummary(name="requests", old_version="2.28.2", new_version="2.28.2"),
        PackageSummary(name="typing-extensions", old_version=None, new_version="4.5.0"),
        PackageSummary(name="urllib3", old_version="1.26.14", new_version="1.26.15"),
    ]
    assert summary == expected

    expected_comment = f"""\
    ### Detected 3 changes to dependencies in Poetry lockfile

    From base new-sha to target old-sha:

    Added **pydantic** (1.10.6)
    Added **typing-extensions** (4.5.0)
    Updated **urllib3** (1.26.14 -> 1.26.15)

    *(2 added, 0 removed, 1 updated, 4 not changed)*

    <small>Generated by diff-poetry-lock {__version__}</small>
    """
    assert (
        format_comment(
            summary,
            base_commit_hash="new-sha",
            target_commit_hash="old-sha",
        )
        or ""
    ).strip() == dedent(expected_comment).strip()


def test_diff_no_changes() -> None:
    old = load_packages(TESTFILE_2)
    new = load_packages(TESTFILE_2)

    summary: list[PackageSummary] = sorted(diff(old, new), key=attrgetter("name"))

    expected = [
        PackageSummary(name="certifi", old_version="2022.12.7", new_version="2022.12.7"),
        PackageSummary(name="charset-normalizer", old_version="3.1.0", new_version="3.1.0"),
        PackageSummary(name="idna", old_version="3.4", new_version="3.4"),
        PackageSummary(name="requests", old_version="2.28.2", new_version="2.28.2"),
        PackageSummary(name="urllib3", old_version="1.26.14", new_version="1.26.14"),
    ]
    assert summary == expected
    assert format_comment(summary) is None


def test_file_loading_missing_file_base_ref(cfg: Settings) -> None:
    with requests_mock.Mocker() as m:
        m.get(
            f"{cfg.api_url}/repos/{cfg.repository}/contents/{cfg.lockfile_path}?ref={cfg.base_ref}",
            request_headers={"Authorization": f"token {cfg.token}", "Accept": "application/vnd.github.raw"},
            status_code=404,
        )

        with pytest.raises(FileNotFoundError):
            do_diff(cfg)


def test_file_loading_missing_file_head_ref(cfg: Settings, data1: bytes) -> None:
    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        m.get(
            f"{cfg.api_url}/repos/{cfg.repository}/contents/{cfg.lockfile_path}?ref={cfg.ref}",
            request_headers={"Authorization": f"token {cfg.token}", "Accept": "application/vnd.github.raw"},
            status_code=404,
        )

        with pytest.raises(FileNotFoundError):
            do_diff(cfg)


def test_e2e_no_diff_existing_comment(cfg: Settings, data1: bytes) -> None:
    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        mock_get_file(m, cfg, data1, cfg.ref)
        comments = [
            {"body": "foobar", "id": 1334, "user": {"id": 123}},
            {"body": "foobar", "id": 1335, "user": {"id": 41898282}},
            {"body": f"{MAGIC_COMMENT_IDENTIFIER}foobar", "id": 1337, "user": {"id": 41898282}},
        ]
        mock_list_comments(m, cfg, comments)
        m.delete(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/comments/1337",
            headers=GithubApi.request_headers(cfg.token),
        )

        do_diff(cfg)


def test_e2e_no_diff_inexisting_comment(cfg: Settings, data1: bytes) -> None:
    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        mock_get_file(m, cfg, data1, cfg.ref)
        mock_list_comments(m, cfg, [])

        do_diff(cfg)


def test_e2e_diff_inexisting_comment(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_2), load_packages(TESTFILE_1)),
        base_commit_hash="new-sha",
        target_commit_hash="old-sha",
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref, resolved_hash="old-sha")
        mock_get_file(m, cfg, data2, cfg.ref, resolved_hash="new-sha")
        mock_resolve_commit_hashes(m, cfg, head_hash="new-sha", base_hash="old-sha")
        mock_list_comments(m, cfg, [])
        m.post(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/{cfg.pr_num}/comments",
            headers=GithubApi.request_headers(cfg.token),
            json={"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}"},
        )

        do_diff(cfg)


def test_e2e_diff_existing_comment_same_data(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_1), load_packages(TESTFILE_2)),
        base_commit_hash="old-sha",
        target_commit_hash="new-sha",
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref, resolved_hash="old-sha")
        mock_get_file(m, cfg, data2, cfg.ref, resolved_hash="new-sha")
        mock_resolve_commit_hashes(m, cfg, head_hash="new-sha", base_hash="old-sha")
        comments = [
            {"body": "foobar", "id": 1334, "user": {"id": 123}},
            {"body": "foobar", "id": 1335, "user": {"id": 41898282}},
            {"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}", "id": 1337, "user": {"id": 41898282}},
        ]
        mock_list_comments(m, cfg, comments)

        do_diff(cfg)


def test_e2e_diff_existing_comment_different_data(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_1), []),
        base_commit_hash="new-sha",
        target_commit_hash="old-sha",
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref, resolved_hash="old-sha")
        mock_get_file(m, cfg, data2, cfg.ref, resolved_hash="new-sha")
        mock_resolve_commit_hashes(m, cfg, head_hash="new-sha", base_hash="old-sha")
        comments = [
            {"body": "foobar", "id": 1334, "user": {"id": 123}},
            {"body": "foobar", "id": 1335, "user": {"id": 41898282}},
            {"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}", "id": 1337, "user": {"id": 41898282}},
        ]
        mock_list_comments(m, cfg, comments)
        m.patch(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/comments/1337",
            headers=GithubApi.request_headers(cfg.token),
            json={"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}"},
        )

        do_diff(cfg)


def test_e2e_diff_commit_lookup_http_failure_falls_back_to_ref(cfg: Settings, data1: bytes, data2: bytes) -> None:
    summary = format_comment(
        diff(load_packages(TESTFILE_2), load_packages(TESTFILE_1)),
        base_commit_hash=cfg.ref,
        target_commit_hash=cfg.base_ref,
    )

    with requests_mock.Mocker() as m:
        mock_get_file(m, cfg, data1, cfg.base_ref)
        mock_get_file(m, cfg, data2, cfg.ref)
        m.post(
            f"{cfg.api_url}/graphql",
            request_headers=GithubApi.request_headers(cfg.token),
            status_code=500,
        )
        mock_list_comments(m, cfg, [])
        m.post(
            f"{cfg.api_url}/repos/{cfg.repository}/issues/{cfg.pr_num}/comments",
            headers=GithubApi.request_headers(cfg.token),
            json={"body": f"{MAGIC_COMMENT_IDENTIFIER}{summary}"},
        )

        do_diff(cfg)


def load_file(filename: Path) -> bytes:
    with filename.open("rb") as f:
        return f.read()


def mock_list_comments(m: Mocker, s: Settings, response_json: list[dict[Any, Any]]) -> None:
    m.get(
        f"{s.api_url}/repos/{s.repository}/issues/{s.pr_num}/comments?per_page=100&page=1",
        request_headers=GithubApi.request_headers(s.token),
        json=response_json,
    )


def mock_get_file(m: Mocker, s: Settings, data: bytes, ref: str, resolved_hash: str | None = None) -> None:
    # The API is requested with Accept: application/vnd.github.raw and should
    # return the raw lockfile bytes. Return the raw bytes as the response body
    # so the code under test can stream/write it to a temp file.
    m.get(
        f"{s.api_url}/repos/{s.repository}/contents/{s.lockfile_path}?ref={ref}",
        request_headers={"Authorization": f"token {s.token}", "Accept": "application/vnd.github.raw"},
        content=data,
    )


def mock_resolve_commit_hashes(
    m: Mocker,
    s: Settings,
    head_hash: str | None = None,
    base_hash: str | None = None,
) -> None:
    response_json = {
        "data": {
            "repository": {
                "head": {"target": {"oid": head_hash}} if head_hash else None,
                "base": {"target": {"oid": base_hash}} if base_hash else None,
            }
        }
    }
    m.post(
        f"{s.api_url}/graphql",
        request_headers=GithubApi.request_headers(s.token),
        json=response_json,
    )


def create_settings(
    repository: str = "user/repo",
    lockfile_path: str = "poetry.lock",
    token: str = "foobar",
    api_url: str = "http://localhost/github_api",
) -> Settings:
    return GitHubActionsSettings(
        event_name="pull_request",
        ref="refs/pull/1/merge",
        repository=repository,
        token=token,
        base_ref="main",
        lockfile_path=lockfile_path,
        api_url=api_url,
    )
